syntax = "proto3";

package api;

option go_package = ".api";

service ServiceCenter {
    rpc DeregisterService (DeregisterServiceRequest) returns (CommonResponse);
    rpc RegisterService (RegisterServiceRequest) returns (CommonResponse);
    rpc Watch (WatchRequest) returns (stream ServicesDiscoverResponse);
    rpc Heartbeat (HeartbeatRequest) returns (CommonResponse);
    rpc Discover (DiscoverRequest) returns (ServicesDiscoverResponse);
}

// ============================= 请求接口 =====================================
// 服务的心跳 request
message HeartbeatRequest {
    string serviceName = 1; // 服务名，如 user-service
    string instanceId = 2;  // 实例唯一ID，可用UUID
}

// 注册某个服务的时候使用的 request
message RegisterServiceRequest {
    string serviceName = 1; // 服务名，如 user-service
    string instanceId = 2;  // 实例唯一ID，可用UUID
    string ip = 3;  // 服务实例IP
    int64 port = 4;   // 服务端口
    string version = 5; // 版本号，支持灰度发布用
    int64 weight = 6; // LB 使用的权重
    map<string,string> metadata = 7;    // 自定义元数据，如 region、env
    int64 ttl = 8;    // 心跳有效期（秒）
}

// 去注册某个服务的时候使用的 request
message DeregisterServiceRequest {
    string serviceName = 1; // 服务名，如 user-service
    string instanceId = 2;  // 实例唯一ID，可用UUID
}

// 监听某个 Service 的 request
message WatchRequest {
    string serviceName = 1;
    int64 event = 2; // INSTANCE_ADDED | INSTANCE_REMOVED | INSTANCE_UPDATED
}

// 发现服务中心的服务
message DiscoverRequest {
    string serviceName = 1;
    string version = 2; // 获取指定版本实例
    string region = 3; // 区域过滤
    bool healthyOnly = 4;  // 是否只返回健康实例
}

// ============================= 消息结构 =====================================

message CommonResponse {
    int64 code = 1;
    string message = 2;
}

message ServicesDiscoverResponse {
    int64 code = 1;
    repeated ServiceInstances services = 2;
}

message ServiceInstances {
    string serviceName = 1; // 服务名，如 user-service
    repeated RegisterServiceRequest instances = 2;
}
