// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: protos/service.proto

package __api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceCenter_DeregisterService_FullMethodName = "/api.ServiceCenter/DeregisterService"
	ServiceCenter_RegisterService_FullMethodName   = "/api.ServiceCenter/RegisterService"
	ServiceCenter_Watch_FullMethodName             = "/api.ServiceCenter/Watch"
	ServiceCenter_Heartbeat_FullMethodName         = "/api.ServiceCenter/Heartbeat"
	ServiceCenter_Discover_FullMethodName          = "/api.ServiceCenter/Discover"
)

// ServiceCenterClient is the client API for ServiceCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceCenterClient interface {
	DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServicesDiscoverResponse], error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServicesDiscoverResponse, error)
}

type serviceCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCenterClient(cc grpc.ClientConnInterface) ServiceCenterClient {
	return &serviceCenterClient{cc}
}

func (c *serviceCenterClient) DeregisterService(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ServiceCenter_DeregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCenterClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ServiceCenter_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCenterClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServicesDiscoverResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceCenter_ServiceDesc.Streams[0], ServiceCenter_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, ServicesDiscoverResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenter_WatchClient = grpc.ServerStreamingClient[ServicesDiscoverResponse]

func (c *serviceCenterClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, ServiceCenter_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCenterClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*ServicesDiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServicesDiscoverResponse)
	err := c.cc.Invoke(ctx, ServiceCenter_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceCenterServer is the server API for ServiceCenter service.
// All implementations must embed UnimplementedServiceCenterServer
// for forward compatibility.
type ServiceCenterServer interface {
	DeregisterService(context.Context, *DeregisterServiceRequest) (*CommonResponse, error)
	RegisterService(context.Context, *RegisterServiceRequest) (*CommonResponse, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[ServicesDiscoverResponse]) error
	Heartbeat(context.Context, *HeartbeatRequest) (*CommonResponse, error)
	Discover(context.Context, *DiscoverRequest) (*ServicesDiscoverResponse, error)
	mustEmbedUnimplementedServiceCenterServer()
}

// UnimplementedServiceCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceCenterServer struct{}

func (UnimplementedServiceCenterServer) DeregisterService(context.Context, *DeregisterServiceRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterService not implemented")
}
func (UnimplementedServiceCenterServer) RegisterService(context.Context, *RegisterServiceRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedServiceCenterServer) Watch(*WatchRequest, grpc.ServerStreamingServer[ServicesDiscoverResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedServiceCenterServer) Heartbeat(context.Context, *HeartbeatRequest) (*CommonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedServiceCenterServer) Discover(context.Context, *DiscoverRequest) (*ServicesDiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedServiceCenterServer) mustEmbedUnimplementedServiceCenterServer() {}
func (UnimplementedServiceCenterServer) testEmbeddedByValue()                       {}

// UnsafeServiceCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCenterServer will
// result in compilation errors.
type UnsafeServiceCenterServer interface {
	mustEmbedUnimplementedServiceCenterServer()
}

func RegisterServiceCenterServer(s grpc.ServiceRegistrar, srv ServiceCenterServer) {
	// If the following call panics, it indicates UnimplementedServiceCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceCenter_ServiceDesc, srv)
}

func _ServiceCenter_DeregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCenterServer).DeregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceCenter_DeregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCenterServer).DeregisterService(ctx, req.(*DeregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCenter_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCenterServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceCenter_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCenterServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCenter_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceCenterServer).Watch(m, &grpc.GenericServerStream[WatchRequest, ServicesDiscoverResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCenter_WatchServer = grpc.ServerStreamingServer[ServicesDiscoverResponse]

func _ServiceCenter_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCenterServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceCenter_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCenterServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCenter_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCenterServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceCenter_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCenterServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceCenter_ServiceDesc is the grpc.ServiceDesc for ServiceCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ServiceCenter",
	HandlerType: (*ServiceCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeregisterService",
			Handler:    _ServiceCenter_DeregisterService_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _ServiceCenter_RegisterService_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ServiceCenter_Heartbeat_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _ServiceCenter_Discover_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ServiceCenter_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/service.proto",
}
