// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================= 请求接口 =====================================
// 服务的心跳 request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"` // 服务名，如 user-service
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`   // 实例唯一ID，可用UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// 注册某个服务的时候使用的 request
type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`                                                                     // 服务名，如 user-service
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`                                                                       // 实例唯一ID，可用UUID
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                                                                                       // 服务实例IP
	Port          int64                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                                                  // 服务端口
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                                                                             // 版本号，支持灰度发布用
	Weight        int64                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`                                                                              // LB 使用的权重
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定义元数据，如 region、env
	Ttl           int64                  `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                                                    // 心跳有效期（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_api_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterServiceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterServiceRequest) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterServiceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterServiceRequest) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RegisterServiceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterServiceRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// 去注册某个服务的时候使用的 request
type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"` // 服务名，如 user-service
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`   // 实例唯一ID，可用UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_api_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterServiceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// 监听某个 Service 的 request
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Event         int64                  `protobuf:"varint,2,opt,name=event,proto3" json:"event,omitempty"` // INSTANCE_ADDED | INSTANCE_REMOVED | INSTANCE_UPDATED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{3}
}

func (x *WatchRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *WatchRequest) GetEvent() int64 {
	if x != nil {
		return x.Event
	}
	return 0
}

// 发现服务中心的服务
type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`          // 获取指定版本实例
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`            // 区域过滤
	HealthyOnly   bool                   `protobuf:"varint,4,opt,name=healthyOnly,proto3" json:"healthyOnly,omitempty"` // 是否只返回健康实例
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DiscoverRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoverRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DiscoverRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{5}
}

func (x *CommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServicesDiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Services      []*ServiceInstances    `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesDiscoverResponse) Reset() {
	*x = ServicesDiscoverResponse{}
	mi := &file_api_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesDiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesDiscoverResponse) ProtoMessage() {}

func (x *ServicesDiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesDiscoverResponse.ProtoReflect.Descriptor instead.
func (*ServicesDiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServicesDiscoverResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServicesDiscoverResponse) GetServices() []*ServiceInstances {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInstances struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ServiceName   string                    `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"` // 服务名，如 user-service
	Instances     []*RegisterServiceRequest `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInstances) Reset() {
	*x = ServiceInstances{}
	mi := &file_api_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstances) ProtoMessage() {}

func (x *ServiceInstances) ProtoReflect() protoreflect.Message {
	mi := &file_api_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstances.ProtoReflect.Descriptor instead.
func (*ServiceInstances) Descriptor() ([]byte, []int) {
	return file_api_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceInstances) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstances) GetInstances() []*RegisterServiceRequest {
	if x != nil {
		return x.Instances
	}
	return nil
}

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12\x03api\"T\n" +
	"\x10HeartbeatRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\"\xc6\x02\n" +
	"\x16RegisterServiceRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x03R\x04port\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x03R\x06weight\x12E\n" +
	"\bmetadata\x18\a \x03(\v2).api.RegisterServiceRequest.MetadataEntryR\bmetadata\x12\x10\n" +
	"\x03ttl\x18\b \x01(\x03R\x03ttl\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x18DeregisterServiceRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\"F\n" +
	"\fWatchRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05event\x18\x02 \x01(\x03R\x05event\"\x87\x01\n" +
	"\x0fDiscoverRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12 \n" +
	"\vhealthyOnly\x18\x04 \x01(\bR\vhealthyOnly\">\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\x18ServicesDiscoverResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x121\n" +
	"\bservices\x18\x02 \x03(\v2\x15.api.ServiceInstancesR\bservices\"o\n" +
	"\x10ServiceInstances\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x129\n" +
	"\tinstances\x18\x02 \x03(\v2\x1b.api.RegisterServiceRequestR\tinstances2\xd4\x02\n" +
	"\rServiceCenter\x12G\n" +
	"\x11DeregisterService\x12\x1d.api.DeregisterServiceRequest\x1a\x13.api.CommonResponse\x12C\n" +
	"\x0fRegisterService\x12\x1b.api.RegisterServiceRequest\x1a\x13.api.CommonResponse\x12;\n" +
	"\x05Watch\x12\x11.api.WatchRequest\x1a\x1d.api.ServicesDiscoverResponse0\x01\x127\n" +
	"\tHeartbeat\x12\x15.api.HeartbeatRequest\x1a\x13.api.CommonResponse\x12?\n" +
	"\bDiscover\x12\x14.api.DiscoverRequest\x1a\x1d.api.ServicesDiscoverResponseB\x06Z\x04/apib\x06proto3"

var (
	file_api_service_proto_rawDescOnce sync.Once
	file_api_service_proto_rawDescData []byte
)

func file_api_service_proto_rawDescGZIP() []byte {
	file_api_service_proto_rawDescOnce.Do(func() {
		file_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)))
	})
	return file_api_service_proto_rawDescData
}

var file_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_service_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),         // 0: api.HeartbeatRequest
	(*RegisterServiceRequest)(nil),   // 1: api.RegisterServiceRequest
	(*DeregisterServiceRequest)(nil), // 2: api.DeregisterServiceRequest
	(*WatchRequest)(nil),             // 3: api.WatchRequest
	(*DiscoverRequest)(nil),          // 4: api.DiscoverRequest
	(*CommonResponse)(nil),           // 5: api.CommonResponse
	(*ServicesDiscoverResponse)(nil), // 6: api.ServicesDiscoverResponse
	(*ServiceInstances)(nil),         // 7: api.ServiceInstances
	nil,                              // 8: api.RegisterServiceRequest.MetadataEntry
}
var file_api_service_proto_depIdxs = []int32{
	8, // 0: api.RegisterServiceRequest.metadata:type_name -> api.RegisterServiceRequest.MetadataEntry
	7, // 1: api.ServicesDiscoverResponse.services:type_name -> api.ServiceInstances
	1, // 2: api.ServiceInstances.instances:type_name -> api.RegisterServiceRequest
	2, // 3: api.ServiceCenter.DeregisterService:input_type -> api.DeregisterServiceRequest
	1, // 4: api.ServiceCenter.RegisterService:input_type -> api.RegisterServiceRequest
	3, // 5: api.ServiceCenter.Watch:input_type -> api.WatchRequest
	0, // 6: api.ServiceCenter.Heartbeat:input_type -> api.HeartbeatRequest
	4, // 7: api.ServiceCenter.Discover:input_type -> api.DiscoverRequest
	5, // 8: api.ServiceCenter.DeregisterService:output_type -> api.CommonResponse
	5, // 9: api.ServiceCenter.RegisterService:output_type -> api.CommonResponse
	6, // 10: api.ServiceCenter.Watch:output_type -> api.ServicesDiscoverResponse
	5, // 11: api.ServiceCenter.Heartbeat:output_type -> api.CommonResponse
	6, // 12: api.ServiceCenter.Discover:output_type -> api.ServicesDiscoverResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
		MessageInfos:      file_api_service_proto_msgTypes,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
